export interface CompanyTenant {
  id: string;
  name: string;
  rfc: string;
  ownerEmail: string;
  avatar: string;
  accentColor: string;
  lightColor: string;
  bgColor: string;
  sucursalDefault: string;
  type: "Matriz" | "Sucursal";
  propietario?: string;
  ownerKey?: string;
  direccion?: string;
  lat?: number;
  lng?: number;
  logoUrl?: string;
  createdAt?: string;
  updatedAt?: string;
}

export const DEFAULT_COMPANY_CATALOG: CompanyTenant[] = [
  {
    id: "tenant-1",
    name: "Los Mas Buscados Los Sombrerudos Xoxo",
    rfc: "SOM160101XOX",
    ownerEmail: "sorayajorge@sombrerudos.mx",
    avatar: "🤠",
    accentColor: "#dc2626",
    lightColor: "#fca5a5",
    bgColor: "from-rose-50 to-red-100",
    sucursalDefault: "Xoxo",
    type: "Matriz",
    propietario: "SORAYA-JORGE",
    ownerKey: "1",
    lat: 17.0654,
    lng: -96.7236,
  },
  {
    id: "tenant-2",
    name: "Los Mas Buscados Los Sombrerudos Plaxa Bella",
    rfc: "SOM160102PBE",
    ownerEmail: "sorayajorge@sombrerudos.mx",
    avatar: "🤠",
    accentColor: "#059669",
    lightColor: "#6ee7b7",
    bgColor: "from-emerald-50 to-teal-100",
    sucursalDefault: "Plaxa Bella",
    type: "Sucursal",
    propietario: "SORAYA-JORGE",
    ownerKey: "1",
    lat: 17.0594,
    lng: -96.7136,
  },
  {
    id: "tenant-3",
    name: "Los Mas Buscados Los Sombrerudos Plaxa Tecno",
    rfc: "SOM160103PTE",
    ownerEmail: "sorayajorge@sombrerudos.mx",
    avatar: "🤠",
    accentColor: "#ca8a04",
    lightColor: "#fde047",
    bgColor: "from-amber-50 to-yellow-100",
    sucursalDefault: "Plaxa Tecno",
    type: "Sucursal",
    propietario: "SORAYA-JORGE",
    ownerKey: "1",
    lat: 17.0754,
    lng: -96.7336,
  },
  {
    id: "tenant-4",
    name: "Los Mas Buscados Los Sombrerudos Plaza Tecno2",
    rfc: "SOM160104PT2",
    ownerEmail: "sorayajorge@sombrerudos.mx",
    avatar: "🤠",
    accentColor: "#2563eb",
    lightColor: "#93c5fd",
    bgColor: "from-blue-50 to-blue-100",
    sucursalDefault: "Plaza Tecno2",
    type: "Sucursal",
    propietario: "SORAYA-JORGE",
    ownerKey: "1",
  },
  {
    id: "tenant-5",
    name: "Taquerias Los Sombrerudos Macro Plaza",
    rfc: "SOM260201MAC",
    ownerEmail: "evelin@sombrerudos.mx",
    avatar: "👒",
    accentColor: "#7c3aed",
    lightColor: "#c084fc",
    bgColor: "from-purple-50 to-purple-100",
    sucursalDefault: "Macro Plaza",
    type: "Matriz",
    propietario: "EVELIN",
    ownerKey: "2",
  },
  {
    id: "tenant-6",
    name: "Los Mero Mero Sombrerudos Universidad",
    rfc: "SOM360301UNI",
    ownerEmail: "armando@sombrerudos.mx",
    avatar: "👑",
    accentColor: "#db2777",
    lightColor: "#f472b6",
    bgColor: "from-pink-50 to-pink-100",
    sucursalDefault: "Universidad",
    type: "Matriz",
    propietario: "ARMANDO",
    ownerKey: "3",
  },
  {
    id: "tenant-7",
    name: "Los Mero Mero Sombrerudos Santa Maria",
    rfc: "SOM460401SMA",
    ownerEmail: "pendiente@sombrerudos.mx",
    avatar: "🎩",
    accentColor: "#14b8a6",
    lightColor: "#99f6e4",
    bgColor: "from-teal-50 to-teal-100",
    sucursalDefault: "Santa Maria",
    type: "Matriz",
    propietario: "PENDIENTE",
    ownerKey: "4",
  },
  {
    id: "tenant-8",
    name: "Taquerias Los Sombrerudos San Sebastian",
    rfc: "SOM560501SSE",
    ownerEmail: "sansebastian@sombrerudos.mx",
    avatar: "🎓",
    accentColor: "#f59e0b",
    lightColor: "#fde047",
    bgColor: "from-amber-50 to-yellow-100",
    sucursalDefault: "San Sebastian",
    type: "Matriz",
    propietario: "SAN SEBASTIAN",
    ownerKey: "5",
  },
  {
    id: "tenant-9",
    name: "Tacos Roy MBravo",
    rfc: "ROY260601MBR",
    ownerEmail: "bladimir@tacosroy.mx",
    avatar: "🌮",
    accentColor: "#ef4444",
    lightColor: "#fca5a5",
    bgColor: "from-red-50 to-orange-100",
    sucursalDefault: "MBravo",
    type: "Matriz",
    propietario: "BLADIMIR",
    ownerKey: "6",
  },
  {
    id: "tenant-10",
    name: "Tacos y Retacos Roy PinoSuarez",
    rfc: "ROY260701PIN",
    ownerEmail: "amparo@tacosroy.mx",
    avatar: "🌯",
    accentColor: "#10b981",
    lightColor: "#a7f3d0",
    bgColor: "from-emerald-50 to-green-100",
    sucursalDefault: "PinoSuarez",
    type: "Matriz",
    propietario: "AMPARO",
    ownerKey: "7",
  },
  {
    id: "tenant-11",
    name: "Tacos y Retacos Roy Etnias",
    rfc: "ROY260702ETN",
    ownerEmail: "amparo@tacosroy.mx",
    avatar: "🌯",
    accentColor: "#14b8a6",
    lightColor: "#99f6e4",
    bgColor: "from-teal-50 to-teal-100",
    sucursalDefault: "Etnias",
    type: "Sucursal",
    propietario: "AMPARO",
    ownerKey: "7",
  },
  {
    id: "tenant-12",
    name: "Tacos y Retacos Roy Viguera",
    rfc: "ROY260801VIG",
    ownerEmail: "levi@tacosroy.mx",
    avatar: "🥗",
    accentColor: "#8b5cf6",
    lightColor: "#ddd6fe",
    bgColor: "from-indigo-50 to-violet-100",
    sucursalDefault: "Viguera",
    type: "Matriz",
    propietario: "LEVI",
    ownerKey: "8",
  },
  {
    id: "tenant-13",
    name: "Tlacolula Tlacolula",
    rfc: "TLA260901TLA",
    ownerEmail: "tlacolula@tacos.mx",
    avatar: "🏛️",
    accentColor: "#ec4899",
    lightColor: "#fbcfe8",
    bgColor: "from-pink-50 to-rose-100",
    sucursalDefault: "Tlacolula",
    type: "Matriz",
    propietario: "TLACOLULA",
    ownerKey: "9",
  },
  {
    id: "tenant-14",
    name: "Crucero Huayapam",
    rfc: "CRU261001HUA",
    ownerEmail: "huayapam@tacos.mx",
    avatar: "🌿",
    accentColor: "#06b6d4",
    lightColor: "#a5f3fc",
    bgColor: "from-cyan-50 to-blue-100",
    sucursalDefault: "Huayapam",
    type: "Matriz",
    propietario: "HUAYAPAM",
    ownerKey: "10",
  },
];
